## This notebook is used to get evaluation results and prepare latex tables. For now the tables are just copy pasted from here to the latex file but they can also as easily be saved to a file

In [1]:
import numpy as np
import pandas as pd
import os
from tqdm.notebook import tqdm

In [2]:
inpath = '../results_main/evaluation_results/intact/'
inpath_eval1 = inpath + 'results_counts_eval1_cgcg_cgnnb_tpfp/'#{}_t{}_{}.txt'.format(c,t, '_'.join(methods))'
inpath_eval2 = inpath + 'results_counts_eval2_cgcg_cgncgnb_tpfp/'#{}_t{}_{}.txt'.format(c,t, '_'.join(methods))'
outpath_eval1 = '../out/latex_tables/eval1_cgcg_cgnnb/'
outpath_eval2 = '../out/latex_tables/eval2_cgcg_cgncgnb/'

if not os.path.exists(outpath_eval1):
    os.makedirs(outpath_eval1)
if not os.path.exists(outpath_eval2):
    os.makedirs(outpath_eval2)

In [4]:
methods = ['discover','discover_strat','fishers','wext']
c = 'COADREAD'
t = 5

infile_eval1 = inpath_eval1+'{}_498_t{}_{}.txt'.format(c,t, '_'.join(methods))#add 498 after + for coadread eg:'{}_498_t{}_{}.txt'
infile_eval2 = inpath_eval2+'{}_498_t{}_{}.txt'.format(c,t, '_'.join(methods))

df1 = pd.read_csv(infile_eval1, sep='\t')
df1

,method,case1,case2,case3,case4,case5,case6,(1+2),(3+6),sgm_allCGNB,...,sgm_allCGNNB,sgm_sigCGNNB,TP,FP,TN,FN,PR,SN(TPR),SP(TNR),F1
0,discover,70.5,7.0,11.0,838.0,765.0,31.5,77.5,42.5,1683.487557,...,1436.858465,257.178538,88.5,49.5,1673.5,1634.5,0.641304,0.051364,0.971271,0.095110
1,discover_strat,21.0,0.0,0.0,876.0,817.0,13.0,21.0,13.0,1264.918917,...,1183.227646,54.278740,21.0,13.0,1714.0,1706.0,0.617647,0.012160,0.992472,0.023850
2,fishers,13.0,0.0,1.0,908.0,816.0,9.0,13.0,10.0,239.165617,...,157.242030,49.921362,14.0,10.0,1737.0,1733.0,0.583333,0.008014,0.994276,0.015810
3,wext,146.0,25.5,32.0,755.0,686.5,52.0,171.5,84.0,2823.804737,...,2247.888727,811.630104,203.5,109.5,1587.5,1493.5,0.650160,0.119918,0.935474,0.202488

In [5]:
columns = df1.columns.tolist()#[:7,9:14,19:]
columns = columns[:1]+columns[2:8]+columns[12:14]+columns[-4:]
columns

['method',
 'case2',
 'case3',
 'case4',
 'case5',
 'case6',
 '(1+2)',
 'sgm_sigCGNNB',
 'TP',
 'PR',
 'SN(TPR)',
 'SP(TNR)',
 'F1']

In [6]:
num_pairs_d1=df1['pairs'].tolist()[0]
num_pairs_d1

KeyError: 'pairs'

In [6]:
new_cols = ['Method', 'Stat1','Stat2','Stat3','Stat4','Stat5','Stat6', 'Stat7', 'Stat8', 'Precision', 'Sensitivity', 'Specificity', 'F1 Score']
dict_methods = {'discover': 'DISCOVER',
               'discover_strat': 'DISCOVER Strat',
               'fishers': 'Fisher\'s Exact Test',
               'megsa': 'MEGSA',
               'memo': 'MEMO',
               'wext': 'WExT'}

In [7]:
decimals = pd.Series([0,1,1,1,1,1,1,3,3, 3,3,3,3], index=columns)
df1_new = df1[columns].round(decimals)
df1_new.columns = new_cols
df1_new

,Method,Stat1,Stat2,Stat3,Stat4,Stat5,Stat6,Stat7,Stat8,Precision,Sensitivity,Specificity,F1 Score
0,discover,28.0,7.0,7.0,83.5,56.5,8.0,2.060,1.444,0.656,0.221,0.884,0.331
1,fishers,6.5,0.0,0.0,115.5,66.0,5.0,0.427,0.260,0.565,0.034,0.974,0.064
2,megsa,10.0,0.0,1.0,16.0,162.0,5.0,1.035,0.899,0.647,0.057,0.969,0.104
3,memo,37.0,9.0,17.0,71.0,47.0,8.5,3.026,1.947,0.646,0.332,0.818,0.439
4,wext,50.0,12.0,15.0,57.0,45.5,9.0,3.991,2.608,0.681,0.408,0.809,0.511

In [8]:
for idx, row in df1_new.iterrows():
    m = row['Method']
    df1_new.at[idx,'Method']=dict_methods[m]
df1_new

,Method,Stat1,Stat2,Stat3,Stat4,Stat5,Stat6,Stat7,Stat8,Precision,Sensitivity,Specificity,F1 Score
0,DISCOVER,28.0,7.0,7.0,83.5,56.5,8.0,2.060,1.444,0.656,0.221,0.884,0.331
1,Fisher's Exact Test,6.5,0.0,0.0,115.5,66.0,5.0,0.427,0.260,0.565,0.034,0.974,0.064
2,MEGSA,10.0,0.0,1.0,16.0,162.0,5.0,1.035,0.899,0.647,0.057,0.969,0.104
3,MEMO,37.0,9.0,17.0,71.0,47.0,8.5,3.026,1.947,0.646,0.332,0.818,0.439
4,WExT,50.0,12.0,15.0,57.0,45.5,9.0,3.991,2.608,0.681,0.408,0.809,0.511

In [10]:
##note: the table here may not be the same format as the one in the latex document. 
##So it is easier to copy the contents and not the headings, begin/end etc
df1_new.to_latex()

"\\begin{tabular}{llrrrrrrrrrrrr}\n\\toprule\n{} &               Method &  Stat1 &  Stat2 &  Stat3 &  Stat4 &  Stat5 &  Stat6 &  Stat7 &  Stat8 &  Precision &  Sensitivity &  Specificity &  F1 Score \\\\\n\\midrule\n0 &             DISCOVER &   28.0 &    7.0 &    7.0 &   83.5 &   56.5 &    8.0 &  2.060 &  1.444 &      0.656 &        0.221 &        0.884 &     0.331 \\\\\n1 &  Fisher's Exact Test &    6.5 &    0.0 &    0.0 &  115.5 &   66.0 &    5.0 &  0.427 &  0.260 &      0.565 &        0.034 &        0.974 &     0.064 \\\\\n2 &                MEGSA &   10.0 &    0.0 &    1.0 &   16.0 &  162.0 &    5.0 &  1.035 &  0.899 &      0.647 &        0.057 &        0.969 &     0.104 \\\\\n3 &                 MEMO &   37.0 &    9.0 &   17.0 &   71.0 &   47.0 &    8.5 &  3.026 &  1.947 &      0.646 &        0.332 &        0.818 &     0.439 \\\\\n4 &                 WExT &   50.0 &   12.0 &   15.0 &   57.0 &   45.5 &    9.0 &  3.991 &  2.608 &      0.681 &        0.408 &        0.809 &     0.511 \\\\\n\\bottomrule\n\\end{tabular}\n"

In [11]:
df2 = pd.read_csv(infile_eval2, sep='\t')
df2

,method,pairs,case1,case2,case3,case4,case5,case6,(1+2),(3+6),...,sgm_allNCGNB,sgm_sigNCGNB,TP,FP,TN,FN,PR,SN(TPR),SP(TNR),F1
0,discover,107,13.0,9.0,7.0,40.0,27.0,10.0,22.0,17.0,...,196.237497,128.830988,29.0,26.0,80.0,77.0,0.527273,0.273585,0.754717,0.360248
1,fishers,107,3.0,0.0,0.0,57.0,41.0,4.0,3.0,4.0,...,49.559860,25.146374,3.0,4.0,101.0,102.0,0.428571,0.028571,0.961905,0.053571
2,megsa,107,7.0,0.0,1.0,10.0,83.0,6.0,7.0,7.0,...,117.466023,30.898741,8.0,7.0,100.0,99.0,0.533333,0.074766,0.934579,0.131148
3,memo,107,16.0,8.5,18.0,34.0,25.0,6.0,24.5,24.0,...,288.766056,235.097216,42.5,32.5,75.0,65.0,0.566667,0.395349,0.697674,0.465753
4,wext,107,18.0,14.0,14.0,29.0,24.0,6.0,32.0,20.0,...,399.210483,342.453502,46.0,34.0,71.0,59.0,0.575000,0.438095,0.676190,0.497297

In [12]:
columns = df2.columns.tolist()#[:7,9:14,19:]
columns = columns[:1]+columns[2:8]+columns[12:14]+columns[-4:]
columns

['method',
 'case1',
 'case2',
 'case3',
 'case4',
 'case5',
 'case6',
 'avg_allCGNB',
 'avg_sigCGNCGB',
 'PR',
 'SN(TPR)',
 'SP(TNR)',
 'F1']

In [13]:
# new_cols = ['Method', 'Case1','Case2','Case3','Case4','Case5','Case6', '$Sigma$ allCGNB', '$Sigma$ sigCGNB', '$Sigma$ allNCGNB', '$Sigma$ sigNCGNB', 'Precision', 'Sensitivity', 'Specificity', 'F1 Score']
dict_methods = {'discover': 'DISCOVER',
               'discover_strat': 'DISCOVER Strat',
               'fishers': 'Fisher\'s Exact Test',
               'megsa': 'MEGSA',
               'memo': 'MEMO',
               'wext': 'WExT'}

In [14]:
decimals = pd.Series([0,1,1,1,1,1,1,3,3, 3,3,3,3], index=columns)
df2_new = df2[columns].round(decimals)
df2_new.columns = new_cols
df2_new

,Method,Stat1,Stat2,Stat3,Stat4,Stat5,Stat6,Stat7,Stat8,Precision,Sensitivity,Specificity,F1 Score
0,discover,13.0,9.0,7.0,40.0,27.0,10.0,2.271,1.834,0.527,0.274,0.755,0.360
1,fishers,3.0,0.0,0.0,57.0,41.0,4.0,0.566,0.463,0.429,0.029,0.962,0.054
2,megsa,7.0,0.0,1.0,10.0,83.0,6.0,1.156,1.098,0.533,0.075,0.935,0.131
3,memo,16.0,8.5,18.0,34.0,25.0,6.0,3.435,2.699,0.567,0.395,0.698,0.466
4,wext,18.0,14.0,14.0,29.0,24.0,6.0,4.611,3.731,0.575,0.438,0.676,0.497

In [15]:
for idx, row in df2_new.iterrows():
    m = row['Method']
    df2_new.at[idx,'Method']=dict_methods[m]
df2_new

,Method,Stat1,Stat2,Stat3,Stat4,Stat5,Stat6,Stat7,Stat8,Precision,Sensitivity,Specificity,F1 Score
0,DISCOVER,13.0,9.0,7.0,40.0,27.0,10.0,2.271,1.834,0.527,0.274,0.755,0.360
1,Fisher's Exact Test,3.0,0.0,0.0,57.0,41.0,4.0,0.566,0.463,0.429,0.029,0.962,0.054
2,MEGSA,7.0,0.0,1.0,10.0,83.0,6.0,1.156,1.098,0.533,0.075,0.935,0.131
3,MEMO,16.0,8.5,18.0,34.0,25.0,6.0,3.435,2.699,0.567,0.395,0.698,0.466
4,WExT,18.0,14.0,14.0,29.0,24.0,6.0,4.611,3.731,0.575,0.438,0.676,0.497

In [16]:
df2_new.to_latex()

"\\begin{tabular}{llrrrrrrrrrrrr}\n\\toprule\n{} &               Method &  Stat1 &  Stat2 &  Stat3 &  Stat4 &  Stat5 &  Stat6 &  Stat7 &  Stat8 &  Precision &  Sensitivity &  Specificity &  F1 Score \\\\\n\\midrule\n0 &             DISCOVER &   13.0 &    9.0 &    7.0 &   40.0 &   27.0 &   10.0 &  2.271 &  1.834 &      0.527 &        0.274 &        0.755 &     0.360 \\\\\n1 &  Fisher's Exact Test &    3.0 &    0.0 &    0.0 &   57.0 &   41.0 &    4.0 &  0.566 &  0.463 &      0.429 &        0.029 &        0.962 &     0.054 \\\\\n2 &                MEGSA &    7.0 &    0.0 &    1.0 &   10.0 &   83.0 &    6.0 &  1.156 &  1.098 &      0.533 &        0.075 &        0.935 &     0.131 \\\\\n3 &                 MEMO &   16.0 &    8.5 &   18.0 &   34.0 &   25.0 &    6.0 &  3.435 &  2.699 &      0.567 &        0.395 &        0.698 &     0.466 \\\\\n4 &                 WExT &   18.0 &   14.0 &   14.0 &   29.0 &   24.0 &    6.0 &  4.611 &  3.731 &      0.575 &        0.438 &        0.676 &     0.497 \\\\\n\\bottomrule\n\\end{tabular}\n"

In [17]:
# print(text1+text2+text3)

# TSN
#this section is for preparing latex files for evaluation on TSN

In [16]:
inpath_tsn = '../out/tsn_gtex/'
inpath_eval1_tsn = inpath_tsn + 'results_tsn_gtex_counts_eval1_cgcg_cgnnb_tpfp/'#{}_t{}_{}.txt'.format(c,t, '_'.join(methods))'
inpath_eval2_tsn = inpath_tsn + 'results_tsn_gtex_counts_eval2_cgcg_cgncgnb_tpfp/'#{}_t{}_{}.txt'.format(c,t, '_'.join(methods))'
outpath_eval1_tsn = '../out/latex_tables/tsn_gtex_eval1_cgcg_cgnnb/'
outpath_eval2_tsn = '../out/latex_tables/tsn_gtex_eval2_cgcg_cgncgnb/'

if not os.path.exists(outpath_eval1_tsn):
    os.makedirs(outpath_eval1_tsn)
if not os.path.exists(outpath_eval2_tsn):
    os.makedirs(outpath_eval2_tsn)

In [17]:
methods = ['discover','discover_strat','fishers','megsa','wext']
c = 'COADREAD'
t = 20
tissue='colon'
tsn_conf_threshold=0.5

infile_eval1_tsn = inpath_eval1_tsn+'{}_t{}_tsnconf{}_{}_{}.txt'.format(c,t,tsn_conf_threshold, tissue,'_'.join(methods))
infile_eval2_tsn = inpath_eval2_tsn+'{}_t{}_tsnconf{}_{}_{}.txt'.format(c,t,tsn_conf_threshold, tissue,'_'.join(methods))

df1_tsn = pd.read_csv(infile_eval1_tsn, sep='\t')
df1_tsn

,method,case1,case2,case3,case4,case5,case6,(1+2),(3+6),sgm_allCGNB,...,sgm_allCGNNB,sgm_sigCGNNB,TP,FP,TN,FN,PR,SN(TPR),SP(TNR),F1
0,discover,27.0,7.0,8.0,66.5,42.0,7.0,34.0,15.0,380.935835,...,262.359122,126.026025,42.0,22.0,135.5,115.5,0.656250,0.266667,0.860317,0.379233
1,discover_strat,7.5,0.0,0.0,94.0,57.0,3.0,7.5,3.0,200.090258,...,153.382917,18.851030,7.5,3.0,158.5,154.0,0.714286,0.046440,0.981424,0.087209
2,fishers,7.0,0.0,0.0,95.0,57.0,5.0,7.0,5.0,83.591617,...,49.646991,27.801971,7.0,5.0,159.0,157.0,0.583333,0.042683,0.969512,0.079545
3,megsa,10.0,0.0,1.0,17.0,132.0,4.0,10.0,5.0,182.161882,...,154.318908,34.794398,11.0,5.0,159.0,153.0,0.687500,0.067073,0.969512,0.122222
4,wext,48.0,12.0,14.0,39.5,36.5,7.0,60.0,21.0,750.820446,...,479.023864,357.933231,74.0,33.0,124.0,83.0,0.691589,0.471338,0.789809,0.560606

In [18]:
columns_tsn = df1_tsn.columns.tolist()#[:7,9:14,19:]
columns_tsn = columns_tsn[:7]+columns_tsn[9:10] + columns_tsn[11:14]+columns_tsn[18:]
columns_tsn

['method',
 'case1',
 'case2',
 'case3',
 'case4',
 'case5',
 'case6',
 'sgm_allCGNB',
 'sgm_sigCGNB',
 'sgm_allCGNNB',
 'sgm_sigCGNNB',
 'PR',
 'SN(TPR)',
 'SP(TNR)',
 'F1']

In [19]:
new_cols = ['Method', 'Case1','Case2','Case3','Case4','Case5','Case6', '$\Sigma$ allCGNB', '$\Sigma$ sigCGNB', '$\Sigma$ allCGNNB', '$\Sigma$ sigCGNNB', 'Precision', 'Sensitivity', 'Specificity', 'F1 Score']
decimals = pd.Series([0,1,1,1,1,1,1, 1,1,1,1,3,3,3,3], index=columns_tsn)
df1_tsn_new = df1_tsn[columns_tsn].round(decimals)
df1_tsn_new.columns = new_cols
df1_tsn_new

,Method,Case1,Case2,Case3,Case4,Case5,Case6,$\Sigma$ allCGNB,$\Sigma$ sigCGNB,$\Sigma$ allCGNNB,$\Sigma$ sigCGNNB,Precision,Sensitivity,Specificity,F1 Score
0,discover,27.0,7.0,8.0,66.5,42.0,7.0,380.9,235.3,262.4,126.0,0.656,0.267,0.860,0.379
1,discover_strat,7.5,0.0,0.0,94.0,57.0,3.0,200.1,28.7,153.4,18.9,0.714,0.046,0.981,0.087
2,fishers,7.0,0.0,0.0,95.0,57.0,5.0,83.6,28.0,49.6,27.8,0.583,0.043,0.970,0.080
3,megsa,10.0,0.0,1.0,17.0,132.0,4.0,182.2,44.6,154.3,34.8,0.688,0.067,0.970,0.122
4,wext,48.0,12.0,14.0,39.5,36.5,7.0,750.8,661.1,479.0,357.9,0.692,0.471,0.790,0.561

In [20]:
for idx, row in df1_tsn_new.iterrows():
    m = row['Method']
    df1_tsn_new.at[idx,'Method']=dict_methods[m]
df1_tsn_new

,Method,Case1,Case2,Case3,Case4,Case5,Case6,$\Sigma$ allCGNB,$\Sigma$ sigCGNB,$\Sigma$ allCGNNB,$\Sigma$ sigCGNNB,Precision,Sensitivity,Specificity,F1 Score
0,DISCOVER,27.0,7.0,8.0,66.5,42.0,7.0,380.9,235.3,262.4,126.0,0.656,0.267,0.860,0.379
1,DISCOVER Strat,7.5,0.0,0.0,94.0,57.0,3.0,200.1,28.7,153.4,18.9,0.714,0.046,0.981,0.087
2,Fisher's Exact Test,7.0,0.0,0.0,95.0,57.0,5.0,83.6,28.0,49.6,27.8,0.583,0.043,0.970,0.080
3,MEGSA,10.0,0.0,1.0,17.0,132.0,4.0,182.2,44.6,154.3,34.8,0.688,0.067,0.970,0.122
4,WExT,48.0,12.0,14.0,39.5,36.5,7.0,750.8,661.1,479.0,357.9,0.692,0.471,0.790,0.561

In [21]:
df1_tsn_new.to_latex()

"\\begin{tabular}{llrrrrrrrrrrrrrr}\n\\toprule\n{} &               Method &  Case1 &  Case2 &  Case3 &  Case4 &  Case5 &  Case6 &  \\$\\textbackslash Sigma\\$ allCGNB &  \\$\\textbackslash Sigma\\$ sigCGNB &  \\$\\textbackslash Sigma\\$ allCGNNB &  \\$\\textbackslash Sigma\\$ sigCGNNB &  Precision &  Sensitivity &  Specificity &  F1 Score \\\\\n\\midrule\n0 &             DISCOVER &   27.0 &    7.0 &    8.0 &   66.5 &   42.0 &    7.0 &             380.9 &             235.3 &              262.4 &              126.0 &      0.656 &        0.267 &        0.860 &     0.379 \\\\\n1 &       DISCOVER Strat &    7.5 &    0.0 &    0.0 &   94.0 &   57.0 &    3.0 &             200.1 &              28.7 &              153.4 &               18.9 &      0.714 &        0.046 &        0.981 &     0.087 \\\\\n2 &  Fisher's Exact Test &    7.0 &    0.0 &    0.0 &   95.0 &   57.0 &    5.0 &              83.6 &              28.0 &               49.6 &               27.8 &      0.583 &        0.043 &        0.970 &     0.080 \\\\\n3 &                MEGSA &   10.0 &    0.0 &    1.0 &   17.0 &  132.0 &    4.0 &             182.2 &              44.6 &              154.3 &               34.8 &      0.688 &        0.067 &        0.970 &     0.122 \\\\\n4 &                 WExT &   48.0 &   12.0 &   14.0 &   39.5 &   36.5 &    7.0 &             750.8 &             661.1 &              479.0 &              357.9 &      0.692 &        0.471 &        0.790 &     0.561 \\\\\n\\bottomrule\n\\end{tabular}\n"

In [22]:
df2_tsn = pd.read_csv(infile_eval2_tsn, sep='\t')
df2_tsn

,method,case1,case2,case3,case4,case5,case6,(1+2),(3+6),sgm_allCGNB,...,sgm_allNCGNB,sgm_sigNCGNB,TP,FP,TN,FN,PR,SN(TPR),SP(TNR),F1
0,discover,13.0,8.0,7.0,26.0,22.0,9.0,21.0,16.0,229.239962,...,186.075679,126.217328,28.0,24.0,61.0,57.0,0.538462,0.329412,0.717647,0.408759
1,discover_strat,5.0,0.0,0.0,40.0,34.0,6.0,5.0,6.0,108.488545,...,98.889137,28.795757,5.0,6.0,79.0,80.0,0.454545,0.058824,0.929412,0.104167
2,fishers,4.0,0.0,0.0,44.0,32.0,4.5,4.0,4.5,60.558581,...,48.292458,22.222002,4.0,4.5,80.0,80.5,0.470588,0.047337,0.946746,0.086022
3,megsa,7.0,0.0,1.0,12.0,61.0,5.0,7.0,6.0,109.108883,...,99.547810,27.283600,8.0,6.0,80.0,78.0,0.571429,0.093023,0.930233,0.160000
4,wext,16.5,14.5,14.0,16.0,18.0,5.0,31.0,19.0,474.248385,...,376.626906,333.970054,45.0,33.5,50.5,39.0,0.573248,0.535714,0.601190,0.553846

In [23]:
columns_tsn = df2_tsn.columns.tolist()#[:7,9:14,19:]
columns_tsn = columns_tsn[:7]+columns_tsn[9:10] + columns_tsn[11:14]+columns_tsn[18:]
columns_tsn

['method',
 'case1',
 'case2',
 'case3',
 'case4',
 'case5',
 'case6',
 'sgm_allCGNB',
 'sgm_sigCGNB',
 'sgm_allNCGNB',
 'sgm_sigNCGNB',
 'PR',
 'SN(TPR)',
 'SP(TNR)',
 'F1']

In [24]:
new_cols = ['Method', 'Case1','Case2','Case3','Case4','Case5','Case6', '$\Sigma$ allCGNB', '$\Sigma$ sigCGNB', '$\Sigma$ allNCGNB', '$\Sigma$ sigNCGNB', 'Precision', 'Sensitivity', 'Specificity', 'F1 Score']
decimals = pd.Series([0,1,1,1,1,1,1, 1,1,1,1,3,3,3,3], index=columns_tsn)
df2_tsn_new = df2_tsn[columns_tsn].round(decimals)
df2_tsn_new.columns = new_cols
df2_tsn_new

,Method,Case1,Case2,Case3,Case4,Case5,Case6,$\Sigma$ allCGNB,$\Sigma$ sigCGNB,$\Sigma$ allNCGNB,$\Sigma$ sigNCGNB,Precision,Sensitivity,Specificity,F1 Score
0,discover,13.0,8.0,7.0,26.0,22.0,9.0,229.2,161.4,186.1,126.2,0.538,0.329,0.718,0.409
1,discover_strat,5.0,0.0,0.0,40.0,34.0,6.0,108.5,22.6,98.9,28.8,0.455,0.059,0.929,0.104
2,fishers,4.0,0.0,0.0,44.0,32.0,4.5,60.6,14.0,48.3,22.2,0.471,0.047,0.947,0.086
3,megsa,7.0,0.0,1.0,12.0,61.0,5.0,109.1,29.0,99.5,27.3,0.571,0.093,0.930,0.160
4,wext,16.5,14.5,14.0,16.0,18.0,5.0,474.2,439.4,376.6,334.0,0.573,0.536,0.601,0.554

In [25]:
for idx, row in df2_tsn_new.iterrows():
    m = row['Method']
    df2_tsn_new.at[idx,'Method']=dict_methods[m]
df2_tsn_new

,Method,Case1,Case2,Case3,Case4,Case5,Case6,$\Sigma$ allCGNB,$\Sigma$ sigCGNB,$\Sigma$ allNCGNB,$\Sigma$ sigNCGNB,Precision,Sensitivity,Specificity,F1 Score
0,DISCOVER,13.0,8.0,7.0,26.0,22.0,9.0,229.2,161.4,186.1,126.2,0.538,0.329,0.718,0.409
1,DISCOVER Strat,5.0,0.0,0.0,40.0,34.0,6.0,108.5,22.6,98.9,28.8,0.455,0.059,0.929,0.104
2,Fisher's Exact Test,4.0,0.0,0.0,44.0,32.0,4.5,60.6,14.0,48.3,22.2,0.471,0.047,0.947,0.086
3,MEGSA,7.0,0.0,1.0,12.0,61.0,5.0,109.1,29.0,99.5,27.3,0.571,0.093,0.930,0.160
4,WExT,16.5,14.5,14.0,16.0,18.0,5.0,474.2,439.4,376.6,334.0,0.573,0.536,0.601,0.554

In [26]:
df2_tsn_new.to_latex()

"\\begin{tabular}{llrrrrrrrrrrrrrr}\n\\toprule\n{} &               Method &  Case1 &  Case2 &  Case3 &  Case4 &  Case5 &  Case6 &  \\$\\textbackslash Sigma\\$ allCGNB &  \\$\\textbackslash Sigma\\$ sigCGNB &  \\$\\textbackslash Sigma\\$ allNCGNB &  \\$\\textbackslash Sigma\\$ sigNCGNB &  Precision &  Sensitivity &  Specificity &  F1 Score \\\\\n\\midrule\n0 &             DISCOVER &   13.0 &    8.0 &    7.0 &   26.0 &   22.0 &    9.0 &             229.2 &             161.4 &              186.1 &              126.2 &      0.538 &        0.329 &        0.718 &     0.409 \\\\\n1 &       DISCOVER Strat &    5.0 &    0.0 &    0.0 &   40.0 &   34.0 &    6.0 &             108.5 &              22.6 &               98.9 &               28.8 &      0.455 &        0.059 &        0.929 &     0.104 \\\\\n2 &  Fisher's Exact Test &    4.0 &    0.0 &    0.0 &   44.0 &   32.0 &    4.5 &              60.6 &              14.0 &               48.3 &               22.2 &      0.471 &        0.047 &        0.947 &     0.086 \\\\\n3 &                MEGSA &    7.0 &    0.0 &    1.0 &   12.0 &   61.0 &    5.0 &             109.1 &              29.0 &               99.5 &               27.3 &      0.571 &        0.093 &        0.930 &     0.160 \\\\\n4 &                 WExT &   16.5 &   14.5 &   14.0 &   16.0 &   18.0 &    5.0 &             474.2 &             439.4 &              376.6 &              334.0 &      0.573 &        0.536 &        0.601 &     0.554 \\\\\n\\bottomrule\n\\end{tabular}\n"